---
title: "R Notebook"
output: html_notebook
---



```{r}
library(dplyr)

# --- 1️⃣ GINI ---
gini <- read.csv("ind_gini_para.csv", 
                 sep = ";", 
                 fileEncoding = "latin1",
                 skip = 2)

gini$gini <- as.numeric(gsub(",", ".", gini$X2010))
gini <- gini[1:(nrow(gini) - 2), ]  # remove as duas últimas linhas
gini <- gini %>% select(Município, gini)  # mantém só o necessário

# --- 2️⃣ Óbitos ---
qtd_obitos <- read.csv("obitos_para.csv",
                       sep = ";",
                       fileEncoding = "latin1",
                       skip = 4)
qtd_obitos$qtd_obitos <- as.numeric(gsub("-", "0", qtd_obitos$Óbitos_p.Ocorrênc))
qtd_obitos <- qtd_obitos %>% select(Município, qtd_obitos)  # mantém só a coluna final

# --- 3️⃣ Óbitos trânsito ---
qtd_obitos_transito <- read.csv("obitos_para_transito.csv",
                                sep = ";",
                                fileEncoding = "latin1",
                                skip = 4)
qtd_obitos_transito$qtd_obitos_transito <- as.numeric(gsub("-", "0", qtd_obitos_transito$Óbitos_p.Ocorrênc))
qtd_obitos_transito <- qtd_obitos_transito %>% select(Município, qtd_obitos_transito)

# --- 4️⃣ População abastecimento água ---
qtd_pop_abastecimento_agua <- read.csv("pop_abastecimento_agua_10.csv",
                                       sep = ";",
                                       fileEncoding = "latin1",
                                       skip = 3)
qtd_pop_abastecimento_agua$qtd_pop_abastecimento_agua <- as.numeric(gsub("-", "0", qtd_pop_abastecimento_agua$Moradores))
qtd_pop_abastecimento_agua <- qtd_pop_abastecimento_agua %>% select(Município, qtd_pop_abastecimento_agua)

# --- 5️⃣ População residente ---
pop <- read.csv("pop_cidade.csv",
                sep = ";",
                fileEncoding = "latin1",
                skip = 3)
pop$pop <- as.numeric(gsub("-", "0", pop$População_residente))
pop <- pop %>% select(Município, pop)

# --- 6️⃣ População coleta de lixo ---
pop_coleta_lixo <- read.csv("pop_coleta_lixo.csv",
                            sep = ";",
                            fileEncoding = "latin1",
                            skip = 3)
pop_coleta_lixo$pop_coleta_lixo <- as.numeric(gsub("-", "0", pop_coleta_lixo$Moradores))
pop_coleta_lixo <- pop_coleta_lixo %>% select(Município, pop_coleta_lixo)

# --- 7️⃣ População instalações sanitárias ---
pop_inst_san <- read.csv("pop_instalacao_san.csv",
                         sep = ";",
                         fileEncoding = "latin1",
                         skip = 3)
pop_inst_san$pop_inst_san <- as.numeric(gsub("-", "0", pop_inst_san$Moradores))
pop_inst_san <- pop_inst_san %>% select(Município, pop_inst_san)

# --- 8️⃣ Taxa de alfabetismo ---
taxa_alf <- read.csv("taxa_alfabetismo_10.csv",
                     sep = ";",
                     fileEncoding = "latin1",
                     skip = 3)
taxa_alf$Taxa_de_analfabetismo <- as.numeric(gsub(",", ".", taxa_alf$Taxa_de_analfabetismo))
taxa_alf <- taxa_alf %>% select(Município, Taxa_de_analfabetismo)

# --- 9️⃣ Taxa de desemprego ---
taxa_desemprego_16_mais <- read.csv("taxa_desemprego_16_mais.csv",
                                    sep = ";",
                                    fileEncoding = "latin1",
                                    skip = 3)
taxa_desemprego_16_mais$taxa_desemprego_16_mais <- as.numeric(gsub(",", ".", taxa_desemprego_16_mais$Taxa_de_desemprego_16a_e.))
taxa_desemprego_16_mais <- taxa_desemprego_16_mais %>% select(Município, taxa_desemprego_16_mais)


```
```{r}
library(readr)
dados_brutos <- read_csv2("Taxa_analf.csv", skip = 3, locale = locale(decimal_mark = ","))



dados_limpos <- dados_brutos %>%
  rename(
    municipio = `Município`,
    situacao_ocupacao = `Situação de ocupação na semana de referência`,
    taxa_analfabetismo_2010 = `2010`
  ) %>%
  mutate(
    taxa_analfabetismo_2010 = as.numeric(gsub(",", ".", taxa_analfabetismo_2010))
  )

dados_para <- dados_limpos %>%
  filter(grepl("\\(PA\\)", municipio))
```
```{r}
qtd_ens_sup <- read_csv2("qtd_ens_sup.csv", skip = 3, locale = locale(decimal_mark = ","))

qtd_ens_sup <- qtd_ens_sup %>%
  filter(grepl("\\(PA\\)", Município)) ; qtd_ens_sup$`Grupo de idade` <-  NULL
```

```{r}
# Função de padronização de texto
padronizar_coluna <- function(texto) {
  texto |>
    # remover siglas entre parênteses (ex: "(PA)")
    (\(x) gsub("\\s*\\([^)]*\\)", "", x))() |>
    # remover acentos
    (\(x) iconv(x, from = "UTF-8", to = "ASCII//TRANSLIT"))() |>
    # converter para minúsculas
    tolower() |>
    # remover números
    (\(x) gsub("[0-9]", "", x))() |>
    # remover espaços extras
    (\(x) gsub("\\s+", " ", x))() |>
    # remover espaços no início e fim
    trimws()
}

# Função automatizada para aplicar em qualquer tabela e coluna
padronizar_tabela <- function(tabela, coluna) {
  tabela$city_tratada <- padronizar_coluna(tabela[[coluna]])
  tabela[[coluna]] <- NULL
  return(tabela)
}

```
```{r}
gini <- padronizar_tabela(gini, "Município")
qtd_obitos <- padronizar_tabela(qtd_obitos, "Município")
qtd_obitos_transito <- padronizar_tabela(qtd_obitos_transito, "Município")
qtd_pop_abastecimento_agua <- padronizar_tabela(qtd_pop_abastecimento_agua, "Município")
pop <- padronizar_tabela(pop, "Município")
pop_coleta_lixo <- padronizar_tabela(pop_coleta_lixo, "Município")
pop_inst_san <- padronizar_tabela(pop_inst_san, "Município")
taxa_alf <- padronizar_tabela(taxa_alf, "Município")
taxa_desemprego_16_mais <- padronizar_tabela(taxa_desemprego_16_mais, "Município")
taxa_anf <- padronizar_tabela(dados_para, "municipio") ; taxa_anf$situacao_ocupacao <- NULL

qtd_ens_sup <- padronizar_tabela(qtd_ens_sup, "Município")
```


```{r}

consolidada <- gini %>%
  left_join(qtd_obitos, by = "city_tratada") %>%
  left_join(qtd_obitos_transito, by = "city_tratada") %>%
  left_join(qtd_pop_abastecimento_agua, by = "city_tratada") %>%
  left_join(pop, by = "city_tratada") %>%
  left_join(pop_coleta_lixo, by = "city_tratada") %>%
  left_join(pop_inst_san, by = "city_tratada") %>%
  left_join(taxa_alf, by = "city_tratada") %>%
  left_join(taxa_desemprego_16_mais, by = "city_tratada")%>%
  left_join(taxa_anf, by = "city_tratada")%>%
  left_join(qtd_ens_sup, by = "city_tratada")

```

